spring:
  application.name: Lab2 Chat Azure
  #  main.web-application-type: none     # Do not start a web server.
  ai:
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
    model.chat: azure-openai
    azure:
      openai:
        api_key: ${AZURE_OPEN_KEY}
        endpoint: https://samsondeploymentmodel.openai.azure.com/
        chat:
          options:
            deployment-name: gpt4-mini
            model: gpt-4o-mini
